### ISSUE TITLE
libgotr client crashes upon Ctrl+C

### ISSUE THREAD

**Issue by totakura** [schachmat/gotr#1]
I observed a crash due to double free upon pressing Ctrl+C.  The following is the stack trace of the crash:

Core was generated by `./client --help'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f26232f4528 in raise () from /usr/lib/libc.so.6

(gdb) bt
#0  0x00007f26232f4528 in raise () from /usr/lib/libc.so.6
#1  0x00007f26232f593a in abort () from /usr/lib/libc.so.6
#2  0x00007f2623332bb2 in __libc_message () from /usr/lib/libc.so.6
#3  0x00007f26233380fe in malloc_printerr () from /usr/lib/libc.so.6
#4  0x00007f26233388db in _int_free () from /usr/lib/libc.so.6
#5  0x0000000000403c4e in gotr_leave (room=0x8ab960) at gotr.c:335
#6  0x00000000004029c7 in cleanup () at client.c:179
#7  0x00000000004029df in handle_sig (signum=6) at client.c:185
#8  <signal handler called>
#9  0x00007f26232f4528 in raise () from /usr/lib/libc.so.6
#10 0x00007f26232f593a in abort () from /usr/lib/libc.so.6
#11 0x00007f2623332bb2 in __libc_message () from /usr/lib/libc.so.6
#12 0x00007f26233380fe in malloc_printerr () from /usr/lib/libc.so.6
#13 0x00007f26233388db in _int_free () from /usr/lib/libc.so.6
#14 0x0000000000403c4e in gotr_leave (room=0x8ab960) at gotr.c:335
#15 0x000000000040307b in main (argc=2, argv=0x7ffddbcde7a8) at client.c:323

(gdb) bt full
#0  0x00007f26232f4528 in raise () from /usr/lib/libc.so.6

No symbol table info available.
#1  0x00007f26232f593a in abort () from /usr/lib/libc.so.6

No symbol table info available.
#2  0x00007f2623332bb2 in __libc_message () from /usr/lib/libc.so.6

No symbol table info available.
#3  0x00007f26233380fe in malloc_printerr () from /usr/lib/libc.so.6

No symbol table info available.
#4  0x00007f26233388db in _int_free () from /usr/lib/libc.so.6

No symbol table info available.
#5  0x0000000000403c4e in gotr_leave (room=0x8ab960) at gotr.c:335

```
    user = 0x3935333230343332
```
#6  0x00000000004029c7 in cleanup () at client.c:179

No locals.
#7  0x00000000004029df in handle_sig (signum=6) at client.c:185

No locals.
#8  <signal handler called>

No symbol table info available.
#9  0x00007f26232f4528 in raise () from /usr/lib/libc.so.6

No symbol table info available.
#10 0x00007f26232f593a in abort () from /usr/lib/libc.so.6

No symbol table info available.
#11 0x00007f2623332bb2 in __libc_message () from /usr/lib/libc.so.6

No symbol table info available.
#12 0x00007f26233380fe in malloc_printerr () from /usr/lib/libc.so.6

No symbol table info available.
#13 0x00007f26233388db in _int_free () from /usr/lib/libc.so.6

No symbol table info available.
#14 0x0000000000403c4e in gotr_leave (room=0x8ab960) at gotr.c:335

```
    user = 0x7ffddbcde6c0
```
#15 0x000000000040307b in main (argc=2, argv=0x7ffddbcde7a8) at client.c:323

```
    lnk = 0x403090 <__libc_csu_init>
    new_user = 0x8aba80
    finfo = {st_dev = 4294967295, st_ino = 140728291157952, st_nlink = 139801775641080, st_mode = 595906560, 
      st_uid = 32550, st_gid = 0, __pad0 = 0, st_rdev = 139801779442877, st_size = 1, st_blksize = 0, 
      st_blocks = 0, st_atime = 139801775610096, st_atimensec = 139801772551496, st_mtime = 2, 
      st_mtimensec = 140728291157928, st_ctime = 139801779469568, st_ctimensec = 1, __glibc_reserved = {
        4206813, 4203312, 0}}
    timeout = {tv_sec = 0, tv_usec = 221916}
    reads = {__fds_bits = {9, 0 <repeats 15 times>}}
    address = {sun_family = 1, sun_path = "--help", '\000' <repeats 101 times>}
    recv_address = {sun_family = 1, 
      sun_path = "sree\000\000\310\035-#&\177\000\000\000Є#&\177\000\000H\345\315\333\375\177\000\000D\345\315\333\375\177\000\000\211\301f#&\177\000\000&\000\000\000\000\000\000\000/\r@\000\000\000\000\000\330\006@\000\000\000\000\000H\345\315\333\375\177\000\000.N=\366\000\000\000\000\070\365\330\003\000\000\000\000.\000\000\000\375\177\000\000 \346\315\333\375\177"}
    recv_address_len = 7
    buf = "u?GOTR?1EayT3CfvtLGmmr47HtIELmq8JYQxX5VnCvA91cAVzJA10bZhe89Gh/vvOiDBJuYANP2k+qoMVXS7WJ/idx2mk2h9QKfld23nVjKfHUFZjqnPNoGJrQ2g79Y4fzVcA7rAtjPClhDCNZ6Z/SznNDnrOAWVfbxZ8fiZDQvf96SgCqI=.", '\000' <repeats 11 times>, "\020\336\315\333\375\177\000\000"...
    buf_len = 181
```

(gdb)

**Comment by schachmat** [comment]
Fixed in #2.
